syntax = "proto3";

option csharp_namespace = "GrpcClient";

package todo;

service TodoItem {
  rpc CreateTodoItem (CreateTodoItemRequest) returns (CreateTodoItemResponse);
  rpc GetTodoItem (GetTodoItemRequest) returns (GetTodoItemResponse);
  rpc GetAllTodoItems (GetAllTodoItemsRequest) returns (GetAllTodoItemsResponse);
}

// The request message containing the user's name.
message CreateTodoItemRequest {
  string Title = 1;
  bool IsCompleted = 2;
}

message CreateTodoItemResponse {
  string message = 1;
  int32 id = 2;
}

message GetTodoItemRequest {
  int32 id = 1;
}
message GetTodoItemResponse {
  int32 id = 1;
  string Title = 2;
  bool IsCompleted = 3;
}

message GetAllTodoItemsRequest {
}
message GetAllTodoItemsResponse {
  repeated GetTodoItemResponse items = 1;
}